### ISSUE TITLE
Awesome List

### ISSUE THREAD

**Issue by malys** [crohit92/express-gateway-plugin-exec#1]
Hi,
You have created express-gateway plugins and i have created a [awesome list](https://github.com/malys/awesome-express-gateway) about this open source project. 
Could you make a pull request to add your projects with a little description in english in the list of plugins?

Thx,

**Comment by crohit92** [comment]
Can you share the link of your repo.

**Comment by malys** [comment]
https://github.com/malys/awesome-express-gateway
